jobs:
  build:
    continue-on-error: true
    name: Build on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14
          - 16
          - 18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Build
        run: npm run build
name: Build
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
