jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14.17.5', '16.13.1', '17.2.0' ]
    name: Build on Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Setup modules
        run: npm i
      - name: Build
        run: npm run build
name: build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
